title: WLHS CAT Club
email: sammidysam@gmail.com
description:
  We're a part of West Lafayette High School and we make cool stuff with code.
baseurl: ""
url: "https://wlcat.tech"
twitter_username: PHP_CEO
github_username:  wl-acsl

markdown: kramdown
theme: minima
